### ISSUE TITLE
Custom CellMatch reference database

### ISSUE THREAD

**Issue by dweemx** [ZJUFanLab/scCATCH#10]
Hi,
I'd like to try scCATCH with a custom CellMatch database (e.g.: for Fly). Is it this possible? If so, how to build one given a list of groups (e.g.: cell types) having each a list of markers ?

**Comment by ZJUFanLab** [comment]
Sorry, scCATCH does not support a custom CellMatch database, but we will develop a similar function to support a custom CellMatch database for users in the future.
