### ISSUE TITLE
wrong number of dimensions

### ISSUE THREAD

**Issue by DanielAmsel** [ZJUFanLab/scCATCH#13]
Hi, me again.
So after running the test code from #4 ,
I wanted to run scCATCH 
`waclu_ann <- scCATCH(Utmarker, species = 'Human', tissue = 'Blood')
`
but I got:
```
Error in object[object$cluster == clu.num[i], ] : 
wrong number of dimensions
```

Do you have a hint for me ?
Kind regards,
Daniel

**Comment by multitalk** [comment]
hello, you should use scCATCH like this. waclu_ann <- scCATCH(Utmarker$clu_markers, species = 'Human', tissue = 'Blood')

**Comment by DanielAmsel** [comment]
Hi @shaoxin0801 ,
thank you very much. Now it works fine for me.
Best regards,
Daniel
