### ISSUE TITLE
Debug! Error in `$<-.data.frame`(`*tmp*`, avg_logfc, value = NaN) : replacement has 1 row, data has 0 

### ISSUE THREAD

**Issue by ZJUFanLab** [ZJUFanLab/scCATCH#2]
If you meet the bug below
```
Error in `$<-.data.frame`(`*tmp*`, avg_logfc, value = NaN) :
replacement has 1 row, data has 0 
```
please re-download and re-install the package os scCATCH for we have fixed this bug!

**Comment by multitalk** [comment]
> If you meet the bug below when run the function of findmarkergenes
> 
> ```
> Error in `$<-.data.frame`(`*tmp*`, avg_logfc, value = NaN) :
> replacement has 1 row, data has 0 
> ```
> 
> please re-download and re-install the package os scCATCH for we have fixed this bug!
