### ISSUE TITLE
CellMatch database updates

### ISSUE THREAD

**Issue by nasiegel88** [ZJUFanLab/scCATCH#21]
Hi, my lab has started using scCATCH to annotate our single cell data from some of our mouse studies and we love it so far. I have a few questions about the CellMatch database:

1. How often is the database updated?
2. What goes into database updates? For example, are single cell annotations from recently published literature added to the database on a regular basis?
3. Will the database updates affect my results if I ran a dataset through scCATCH at an earlier time.

Again, great work! love the package.

**Comment by multitalk** [comment]
Thanks for your attention. We plan to update the database next year by revising the marker gene symbols according to the NCBI Gene database. Basically, the database will not affect your results.

**Comment by nasiegel88** [comment]
Thank you for the quick response and information. Also, are the number of cell markers identified in a given dataset fixed? Is there potential to identify additional markers if a new publication identifies a cell type and classifies it with an additional marker that is different from what had been previously published?

**Comment by multitalk** [comment]
Hello, we will add more markers into CellMatch if high-quality markers are applicable.
