### ISSUE TITLE
cell type identification

### ISSUE THREAD

**Issue by lvweiming** [ZJUFanLab/scCATCH#22]
I have 20 clusters. but only 5 of them have cell-type identification after running with scCATCH. other still showing clusters number instead of the cell type.
Can anyone tell what could be reasons and how to fix it?
![sccatch](https://user-images.githubusercontent.com/38509650/101094549-33710e80-3582-11eb-8383-9bd389cf9251.png)

**Comment by multitalk** [comment]
Hello, there are two solutions you can try. 

(1) Adjust the parameters in `findmarkergenes()` by setting a lower `cell_min_pct` and `logfc`, e.g., `cell_min_pct = 0.1`, `logfc = 0.1`, and run `scCATCH()` again.

```
clu_markers <- findmarkergenes(Seurat_object,cell_min_pct = 0.1, logfc = 0.1)
clu_ann <- scCATCH(clu_markers)
```

(2) Use `FindAllMarkers()` of Seurat, and run `scCATCH()` again.
```
clu_markers <- FindAllMarkers(Seurat_object)
clu_ann <- scCATCH(clu_markers)
```

**Comment by lvweiming** [comment]
> Hello, there are two solutions you can try.
> 
> (1) Adjust the parameters in `findmarkergenes()` by setting a lower `cell_min_pct` and `logfc`, e.g., `cell_min_pct = 0.1`, `logfc = 0.1`, and run `scCATCH()` again.
> 
> ```
> clu_markers <- findmarkergenes(Seurat_object,cell_min_pct = 0.1, logfc = 0.1)
> clu_ann <- scCATCH(clu_markers)
> ```
> 
> (2) Use `FindAllMarkers()` of Seurat, and run `scCATCH()` again.
> 
> ```
> clu_markers <- FindAllMarkers(Seurat_object)
> clu_ann <- scCATCH(clu_markers)
> ```

**Comment by lvweiming** [comment]
> Hello, there are two solutions you can try.
> 
> (1) Adjust the parameters in `findmarkergenes()` by setting a lower `cell_min_pct` and `logfc`, e.g., `cell_min_pct = 0.1`, `logfc = 0.1`, and run `scCATCH()` again.
> 
> ```
> clu_markers <- findmarkergenes(Seurat_object,cell_min_pct = 0.1, logfc = 0.1)
> clu_ann <- scCATCH(clu_markers)
> ```
> 
> (2) Use `FindAllMarkers()` of Seurat, and run `scCATCH()` again.
> 
> ```
> clu_markers <- FindAllMarkers(Seurat_object)
> clu_ann <- scCATCH(clu_markers)
> ```

Thank you for answer my question. the second method solves my problem.
