### ISSUE TITLE
Cluster with multiple cell types

### ISSUE THREAD

**Issue by lvweiming** [ZJUFanLab/scCATCH#23]
HI, after running with scCATCH, I have some clusters identified with more than one cell type. Is this normal? should it be one cell type per cluster? What could be the reasons?

**Comment by multitalk** [comment]
Sorry for getting back to you so late. It is normal that a cluster is assigned with two cell types if they have the same scores. Under this case, you can try different parameters or use cell marker genes from `FindAllMarkers` of `Seurat`.

**Comment by lvweiming** [comment]
> Sorry for getting back to you so late. It is normal that a cluster is assigned with two cell types if they have the same scores. Under this case, you can try different parameters or use cell marker genes from `FindAllMarkers` of `Seurat`.

Thank you for the clarification.
