### ISSUE TITLE
cancer type的参数设置问题

### ISSUE THREAD

**Issue by lxwang326** [ZJUFanLab/scCATCH#24]
老师您好，看了您写的scCATCH，没看到例子中关于癌症的举例，我想咨询一个关于cancer type的参数设置问题。
以Acute Myelogenous Leukemia: Blood.为例，
1.	Cancer type是应该选前面的Acute Myelogenous Leukemia，还是后面的Blood？
Cancer = Acute Myelogenous Leukemia?
Or 
Cancer = Blood?
2.	能不能同时选择两个cancer type?
如果我是选两个cancer type 比如肺癌和肝癌，
Liver Cancer: Blood; Liver
Lung Adenocarcinoma: Lung
Cancer= c(‘Blood’,’Liver’,’ Lung’)
是不是后面做scCATCH的时候tissue必须在在肝癌和肺癌这两个参数包含的组织中选择，而不能选择比如淋巴瘤所属的组织？
谢谢
3.	Findmaker和scCATCH的癌症类型和组织detail参数为什么不设一致？

**Comment by multitalk** [comment]
您好，目前scCATCH还没有允许同时选择肿瘤组织和正常组织，后面会更新这个功能，所以cancer type应该选Acute Myelogenous Leukemia；可以同时选择两个cancer type；Findmaker和scCATCH的癌症类型和组织detail参数应该是一样的。

**Comment by lxwang326** [comment]
谢谢回复
