### ISSUE TITLE
object not interpretable as a factor

### ISSUE THREAD

**Issue by lxwang326** [ZJUFanLab/scCATCH#25]
hi ，can you help me？
what's wrong with the problem？

clu_ann <- scCATCH(clu_markers$clu_markers,
+                    species = "Mouse",
+                    cancer = C('Lung Cancer','Lung Adenocarcinoma','Non-Small Cell Lung Cancer'),
+                    tissue = C('Airway epithelium','Alveolus','Bronchoalveolar system','Lung','Blood','Peripheral blood'))
Error in C("Lung Cancer", "Lung Adenocarcinoma", "Non-Small Cell Lung Cancer") : 
  object not interpretable as a factor

**Comment by multitalk** [comment]
您好，数据库里小鼠的cancer type没有'Lung Adenocarcinoma','Non-Small Cell Lung Cancer'，只有Lung Cancer，所以这个参数只能是
```
scCATCH(clu_markers$clu_markers, species = 'Mouse', cancer = 'Lung Cancer', tissue = 'Lung')
```
组织类型只能选择当前癌症有的组织类型

**Comment by lxwang326** [comment]
thank you！
