### ISSUE TITLE
scCATCH with Spatial data

### ISSUE THREAD

**Issue by raman91** [ZJUFanLab/scCATCH#26]
Hello,
Is it possible to run scCATCH with Spatial dataset?
When i run findmarkergenes, i get an Error: Cannot find 'RNA' in this Seurat object

Best Regards

**Comment by multitalk** [comment]
Hello, the current version of scCATCH doesn't support the Spatial dataset. My understanding is that you can ignore the spatial information of the data matrix and process it as a common scRNA-seq data with Seurat. After annotating the cell types, you can map the cell types between two Seurat objects with the `Cell_ID` using `Idents()`. The future version of scCATCH will support the Seurat object based on Spatial datasets. Thanks for your suggestions.
