### ISSUE TITLE
SCTransform compatibility with scCATCH

### ISSUE THREAD

**Issue by bounlu** [ZJUFanLab/scCATCH#28]
The `scCATCH` document says use `log1p` normalization as the default method of `Normalizedata` function in `Seurat`. However, in later versions of `Seurat`, `SCTransform` is integrated and suggested which replaces several steps including the normalization. Does it still use the same method of `log1p` as suggested? Is such normalized `Seurat` object still safe and good to use with `scCATCH`?

**Comment by diyang1354** [comment]
After SCTransform workflow, there still exists an assay called 'RNA'. You can use NormalizeData function in Seurat on this 'RNA' assay and the log1p data is stored in the 'data' slot under 'RNA' assay.

**Comment by bounlu** [comment]
Indeed I proceeded with `SCT` assay and it still worked fine in my case. However, `findallmarkers` from `scCATCH` didn't work fine as later not all my clusters were assigned to cell types, however `FindAllMarkers` function from `Seurat` worked great and `scCATCH` could only after that find cell types for all clusters.

**Comment by multitalk** [comment]
Hello, `findmarkergenes` is to find the specifically highly expressed genes for each cluster which is more strict than the `FindAllMarkers`. So, some clusters may be assigned with no cell types as no marker genes found when there are lots of clusters. Under this condition, `FindAllMarkers` is a good choice. `findmarkergenes` is more proper for scRNA-seq datasets with limited clusters.
