### ISSUE TITLE
Loosing a large number of genes when running findmarkergenes

### ISSUE THREAD

**Issue by nasiegel88** [ZJUFanLab/scCATCH#30]
When I run:
`
require('scCATCH')
clu_markers_combined <- findmarkergenes(object = ets.integrated,
                                                species = 'Mouse',
                                                cluster = 'All',
                                                match_CellMatch = FALSE,
                                                cancer = NULL,
                                                tissue = NULL,
                                                cell_min_pct = 0.25,
                                                logfc = 0.25,
                                                pvalue = 0.05)
set.seed(1)
`

I noticed I was getting no cells to match to my clusters but then I looked at the output from before sscatch starts finding markers:
`
Note: the raw data matrix includes 13722 cells and 36601 genes. 

---Revising gene symbols according to NCBI Gene symbols (updated in June 19, 2020, https://www.ncbi.nlm.nih.gov/gene) and no matched genes and duplicated genes will be removed. 

Note: the new data matrix includes 13722 cells and 214 genes.
`

Do you have any idea why my raw data matrix has over 3000 genes (which makes sense) but the new data matrix only has 214 genes. I suspect this is the reason why sscatch is identifying almost no cell types in my data.

Thank you in advance

**Comment by multitalk** [comment]
You should check the gene name of the raw data matrix. Make sure they are official gene symbols instead of the gene ID or Ensembl ID.

**Comment by nasiegel88** [comment]
Thank you for your help. It seems I downloaded the human reference genome from 10x, when I needed mouse. I suspect when my batch re-submit is complete the scCATCH workflow should run without a hitch.
