### ISSUE TITLE
new markers added to cellMatch or scCATCH

### ISSUE THREAD

**Issue by Jasonliu21** [ZJUFanLab/scCATCH#31]
Is there a way to add new marker genes to the original cellMatch in the package,  or customized marker list used in scCATCH ?

**Comment by multitalk** [comment]
I‘m so sorry for my delay in writing back, but I've been very busy working recently. Now,  the v3.0 allows you to add new marker genes to the original cellMatch and you can have a try. I hope this updation can help you anyway. Good Luck.
