### ISSUE TITLE
Cancer tissues for mouse

### ISSUE THREAD

**Issue by olgabaranov** [ZJUFanLab/scCATCH#36]
I am very happy with the tools performance on human tissue. Thanks for hat!
Now, trying to run an analysis of pancreatic tumors in mouse I find the tissue associated with it lacking and close to no clusters are annotated when run like that. Will there be updates to the tissues / cancers in mouse soon?
(I know that there is probably a workaround to analyse the sample with no cancer argument and more relevant tissues first and then repeat the analysis with tissue='Blood' and cancer='Pancreatic Cancer' but nor do I know whether it is right and safe way to do nor does it seem to be an optimal workflow).

**Comment by multitalk** [comment]
I‘m so sorry for my delay in writing back, but I've been very busy working recently. Now, the v3.0 allows you to use different combination of tissue and cancer in cellMatch and you can have a try. I hope this updation can help you anyway. Good Luck.
