### ISSUE TITLE
Creating UMAP and PCA Plots after Cluster Annotation and Marker Identification

### ISSUE THREAD

**Issue by phoebe460** [ZJUFanLab/scCATCH#37]
Hello scCATCH developers,

First off, thanks for creating this great tool. I am using it now for my single-cell analysis, and it's been working great so far. 

So I've done the following for my analysis:

`clu_markers <- findmarkergenes(cells_human_tc,
                               species = 'Human',
                               cluster = 'All',
                               match_CellMatch = FALSE,
                               cancer = NULL,
                               tissue = c('Brain','Dorsolateral prefrontal cortex'),
                               cell_min_pct = 0.1, #as recommended by Issues Github page
                               logfc = 0.1, #as recommended by Issues Github page
                               pvalue = 0.05)`

`clu_ann <- scCATCH(clu_markers_v2, species = 'Human', tissue = 'Brain')`

Since I have the markers and annotated clusters identified, is there a way to get UMAP and PCA plots from this? If so, is there a way to visualize my annotated clusters code wise? If you can help out with this, then that would be greatly appreciated. 

Thanks,
Phoebe

**Comment by multitalk** [comment]
I suggest to use `Seurat` to get UMAP and PCA plots.
