### ISSUE TITLE
Interested in combining cancer and non-cancer

### ISSUE THREAD

**Issue by SimoniMD** [ZJUFanLab/scCATCH#38]
Hi there,

I'm dealing with immune cells during pregnancy, and they can be related to oncogenic conditions (pregnancy is sometimes considered cancer-like), or they may not. Is there a way to have scCatch match to cancer and non-cancer tissues at the same time?

Thanks!

**Comment by multitalk** [comment]
I‘m so sorry for my delay in writing back, but I've been very busy working recently. Now, the v3.0 allows you to use different combination of tissue and cancer in cellMatch and you can have a try. I hope this updation can help you anyway. Good Luck.
