### ISSUE TITLE
All the same cell type when using scCATCH on Seurat FindAllMarkers

### ISSUE THREAD

**Issue by darlene003** [ZJUFanLab/scCATCH#39]
I'm trying to use my Seurat markers (via FindAllMarkers) with the scCATCH function.  The data is hippocampus in the mouse, so I am using species='Mouse' and tissue='Brain'.

The output shows different cluster_markers for each cluster, but all the other columns are the same:  cell_type=,"Astrocyte", cell_type_score=.97, same related markers, and same PMID's.

We have done a manual annotation of cell types on my FindAllMarkers file, and the markers within each cluster make sense.  We were trying to validate it with scCATCH.  Do you know why I would get the same cell type for every cluster?

**Comment by multitalk** [comment]
Maybe you can try different parameters to figure it out.
