### ISSUE TITLE
only 5 potential marker genes in CellMatch database for Mouse on Skin

### ISSUE THREAD

**Issue by Tommaso12** [ZJUFanLab/scCATCH#40]
Hi, I am analysing a dataset from treated ear mouse skin. By applying `findmarkergenes` and after revising the gene symbols (with no matched genes and duplicated genes removed) the raw data matrix includes 17663 cells and 16227 genes ( so I thought quite good!).
But then warning message: "there are only 5 potential marker genes in CellMatch database for Mouse on Skin!" 
I set up cluster = 'All', and again: "there is no potential marker genes found in the matrix! You may adjust the cell clusters by applying other clustering algorithm and try again"... I find it really wierd. 
Which other clustering algorithm may I try?
Note: I am actually working on an integrated object of controls and treatment. Might this influence the outcome?
Thank you a lot for your help!

**Comment by multitalk** [comment]
I‘m so sorry for my delay in writing back, but I've been very busy working recently. Now, the v3.0 allows you to use different combination of tissue in cellMatch and you can have a try with more tissues related with skin. I hope this updation can help you anyway. Good Luck.

**Comment by Tommaso12** [comment]
No worries! I will try the v3.0! Thank you a lot!
