### ISSUE TITLE
Tissue choice

### ISSUE THREAD

**Issue by lwtan90** [ZJUFanLab/scCATCH#41]
Hi,

I am dealing with a bunch of immature cell types. I am wondering if there is a way for your method to scan through all tissue types to annotate the cell type?

Wilson

**Comment by multitalk** [comment]
I‘m so sorry for my delay in writing back, but I've been very busy working recently. Now, the v3.0 allows you to use different combination of tissue and cancer in cellMatch and you can have a try with a scan through all tissue types to annotate the cell type. I hope this updation can help you anyway. Good Luck.
