### ISSUE TITLE
How to download all cell markers in a certain tissue embbed in this package?

### ISSUE THREAD

**Issue by JiahuaQu** [ZJUFanLab/scCATCH#43]
I want to download or output the cell types and markers in a certain mouse tissue. I found that this page, https://github.com/ZJUFanLab/scCATCH/wiki/mouse_tissues, listed the tissues, but didn't find a way to observe the contents (cell types and marker genes). I want to observe them to know how to interpret the results better and to curate or modify them according to my specific project. Thank you.

**Comment by multitalk** [comment]
Hello, all cell types and markers can be found in [`cellmatch.rda`](https://github.com/ZJUFanLab/scCATCH/blob/master/data/cellmatch.rda)

**Comment by JiahuaQu** [comment]
Thank you so much for the data.
