### ISSUE TITLE
Could not find function

### ISSUE THREAD

**Issue by VNa24** [ZJUFanLab/scCATCH#44]
I have installed scCATCH package and run the following code.

library(scCATCH)
Markers <- findmarkergenes(combined,
                          species = "Mouse",
                          cluster = 'All',
                          match_CellMatch = FALSE,
                          cancer = NULL,
                          tissue = "Skin",
                          cell_min_pct = 0.25,
                          logfc = 0.25,
                          pvalue = 0.05)

But it's showing the following error:
Error in findmarkergenes(combined, species = "Mouse", cluster = "All",  : 
  could not find function "findmarkergenes"

I have run scCATCH analyses before and have never encountered this problem. Could anyone assist me with this issue, please?

**Comment by multitalk** [comment]
Please refer to [https://raw.githack.com/ZJUFanLab/scCATCH/master/vignettes/tutorial.html](https://raw.githack.com/ZJUFanLab/scCATCH/master/vignettes/tutorial.html)

**Comment by xiaoxiaofuyou** [comment]
> Please refer to https://raw.githack.com/ZJUFanLab/scCATCH/master/vignettes/tutorial.html
Thank you. But why i can't open this address? like this
![image](https://user-images.githubusercontent.com/105490459/168261938-62df17dd-cd82-4a9f-bfcf-e22655c7e1ba.png)
I have tried Google brower and Microsoft brower.

**Comment by xiaoxiaofuyou** [comment]
Because I had the same problem today, saying i can't find this function——'findmarkergenes', I would appreciate it very much if you can answer my question.

**Comment by multitalk** [comment]
Hello, scCATCH v3.0 have two functions, namely `findmarkergene()` and `findcelltype()`  replacing the functions of `findmarkergenes()` and `scCATCH()` in the previous version, respectively. Given the `tutorial.html`, you can download the file from the https://github.com/ZJUFanLab/scCATCH/blob/master/vignettes/tutorial.html and open it in your own browser locally.
