### ISSUE TITLE
Cholmod error 'problem too large' 

### ISSUE THREAD

**Issue by oldedios** [ZJUFanLab/scCATCH#45]
Hi, I am analyzing a large dataset and in the step for finding highly expressed genes with _findmarkergene_ I have the following ERROR:

Error in asMethod(object) : __
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

Do you have any suggestions to resolve it?

Thank you a lot for your help!

**Comment by multitalk** [comment]
Maybe you need a more powerful server to run it
