### ISSUE TITLE
An error for scCATCH

### ISSUE THREAD

**Issue by KaWingLee9** [ZJUFanLab/scCATCH#47]
When runing scCATCH, following bug occurs:

> scCATCH_markers <- findmarkergene(scCATCH_obj,species=c('Human'),cluster = 'All',marker=cellmatch,cancer = 'Breast Cancer',tissue = 'Breast',cell_min_pct = 0.25,logfc = 0.25,pvalue = 0.05)
There are 537 potential marker genes in CellMatch database for Human Breast Cancer on Breast.
[+++++>------------------------] Finished: 19% Time 00:00:01Error in `$<-.data.frame`(`*tmp*`, "cluster", value = "3") : 
  replacement has 1 row, data has 0

**Comment by multitalk** [comment]
Hello, I have fixed the bug and you can try again by re-installing `scCATCH` using `devtools::install_github('ZJUFanLab/scCATCH')`

**Comment by KaWingLee9** [comment]
您的邮件我已收到，但如果重要通知请以我亲自回复收到为准！感谢！
