### ISSUE TITLE
Problem with functions findmarkergenes and scCATCH

### ISSUE THREAD

**Issue by celineyayifeng** [ZJUFanLab/scCATCH#48]
Hello, 

I am running into an issue when I ran these two functions (example code provided below): 

`clu_markers <- findmarkergenes(Seurat_object,cell_min_pct = 0.1, logfc = 0.1)
clu_ann <- scCATCH(clu_markers)`

It returned the following error messages: 

could not find function "findmarkergenes" or could not find function "scCATCH"

I have seen people who used these functions in the past. Is this a change to the scCATCH package and the current version no longer uses these functions? I am also trying to map the cell types that are identified by scCATCH to a UMAP plot generated by Seurat. What would be the current method in approaching this problem? Thank you!

**Comment by multitalk** [comment]
Please refer to https://raw.githack.com/ZJUFanLab/scCATCH/master/vignettes/tutorial.html

**Comment by multitalk** [comment]
[see issue 44](https://github.com/ZJUFanLab/scCATCH/issues/44)
