### ISSUE TITLE
ERROR :    unable to find an inherited method for function ‘findmarkergene’ for signature ‘"Seurat"’

### ISSUE THREAD

**Issue by levinhein** [ZJUFanLab/scCATCH#49]
Hello. May I ask how to resolve this error?

`obj <- findmarkergene(object = KD.harmony, species = "Human", marker = cellmatch, tissue = "Blood")`

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘findmarkergene’ for signature ‘"Seurat"’
```
Thank you.

**Comment by multitalk** [comment]
Hello, the latest version of scCATCH does not need Seurat object. You can follow the [tutorial]( https://raw.githack.com/ZJUFanLab/scCATCH/master/vignettes/tutorial.html) to use a `scCATCH` object instead.

**Comment by mbartl13** [comment]
Hello- similar issue but when I go to make a ssCATCH object I get an error too:
`obj <- createscCATCH(data = CPobj, cluster = CPobj_clusters)`
Error in createscCATCH(data = CPobj, cluster = CPobj_clusters) : 
  count is not a matrix or dgCMatrix! See demo_data()

**Comment by multitalk** [comment]
You can try `obj <- createscCATCH(data = as.matrix(CPobj), cluster = CPobj_clusters)`
