### ISSUE TITLE
Issue with scCATCH

### ISSUE THREAD

**Issue by rmondragon90** [ZJUFanLab/scCATCH#5]
Hello, I am having the following error when running scCATCH:

`WT_baseline_all_markers<-findmarkergenes(WT_baseline_all, species = 'Mouse', cluster = 'All', match_CellMatch = TRUE, tissue = 'Aorta')`
 Note: the raw data matrix includes 6836 cells and 17964 genes.   ---Revising gene symbols according to NCBI Gene symbols (updated in Jan. 10, 2020, https://www.ncbi.nlm.nih.gov/gene) and no matched genes and duplicated genes will be removed.   Note: the new data matrix includes 6836 cells and 17288 genes.   Warning: there are only 45 potential marker genes in CellMatch database for Mouse on Aorta!   Finding potential marker genes for cluster 0  ***Done***  Finding potential marker genes for cluster 1  ***Done***  Finding potential marker genes for cluster 2  ***Done***  Finding potential marker genes for cluster 3  ***Done***  Finding potential marker genes for cluster 4  ***Done***  Finding potential marker genes for cluster 5  ***Done***  Finding potential marker genes for cluster 6  ***Done***  Finding potential marker genes for cluster 7  ***Done***  Finding potential marker genes for cluster 8  ***Done***  
`WT_baseline_clusters < scCATCH(WT_baseline_all_markers$WT_baseline_all_markers, cancer = NULL,  species = 'Mouse', tissue = 'Aorta')`
 Warning: there are only 45 potential marker genes in CellMatch database for Mouse on Aorta!   Note: there are 10 cell types in CellMatch database for Mouse on Aorta!   Beginning evidence-based scoring and annotation  Error in data.frame(cluster = clu.num[i], cluster_marker = rescluster_marker1,  :    arguments imply differing number of rows: 1, 0

Thank you

**Comment by ZJUFanLab** [comment]
Hello, can you show me the detail of `WT_baseline_all_markers$WT_baseline_all_markers` as the default `WT_baseline_all_markers` generated from`findmarkergenes` contains a `clu_markers` data.frame. Besides, I checked the source code and assume this error might be that there is no marker genes for some clusters in the `clu_markers`, and I have tried to fixed this bug, you can re-download and re-install the package os scCATCH.

**Comment by rmondragon90** [comment]
Hi, I have updated  the package and now it looks like this:
`> WT_baseline_all_markers<-findmarkergenes(WT_baseline_all, species = 'Mouse', cluster = 'All')`
Note: the raw data matrix includes 6836 cells and 17964 genes. 

---Revising gene symbols according to NCBI Gene symbols (updated in Jan. 10, 2020, https://www.ncbi.nlm.nih.gov/gene) and no matched genes and duplicated genes will be removed. 

Note: the new data matrix includes 6836 cells and 17288 genes. 

Finding potential marker genes for cluster 0 
***Done*** 
Finding potential marker genes for cluster 1 
***Done*** 
Finding potential marker genes for cluster 2 
***Done*** 
Finding potential marker genes for cluster 3 
***Done*** 
Finding potential marker genes for cluster 4 
***Done*** 
Finding potential marker genes for cluster 5 
***Done*** 
Finding potential marker genes for cluster 6 
***Done*** 
Finding potential marker genes for cluster 7 
***Done*** 
Finding potential marker genes for cluster 8 
***Done*** 
`> WT_baseline_clusters <- scCATCH(WT_baseline_all_markers, cancer = NULL,  species = 'Mouse', tissue = 'Aorta')`
Error: lazy-load database '/home/mondrri1/R/x86_64-pc-linux-gnu-library/3.6/scCATCH/R/scCATCH.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error -3 in R_decompress1

I tried re-installing again but the error persists. Thank you

**Comment by rmondragon90** [comment]
Hi, 
I have re installed the package:

`> WT_baseline_all_markers<-findmarkergenes(WT_baseline_all, species = 'Mouse', cluster = 'All')`
Note: the raw data matrix includes 6836 cells and 17964 genes. 

---Revising gene symbols according to NCBI Gene symbols (updated in Jan. 10, 2020, https://www.ncbi.nlm.nih.gov/gene) and no matched genes and duplicated genes will be removed. 

Note: the new data matrix includes 6836 cells and 17288 genes. 

Finding potential marker genes for cluster 0 
***Done*** 
Finding potential marker genes for cluster 1 
***Done*** 
Finding potential marker genes for cluster 2 
***Done*** 
Finding potential marker genes for cluster 3 
***Done*** 
Finding potential marker genes for cluster 4 
***Done*** 
Finding potential marker genes for cluster 5 
***Done*** 
Finding potential marker genes for cluster 6 
***Done*** 
Finding potential marker genes for cluster 7 
***Done*** 
Finding potential marker genes for cluster 8 
***Done*** 

`> WT_baseline_clusters <- scCATCH(WT_baseline_all_markers, cancer = NULL,  species = 'Mouse', tissue = 'Aorta')`
Warning: there are only 45 potential marker genes in CellMatch database for Mouse on Aorta! 

Note: there are 10 cell types in CellMatch database for Mouse on Aorta! 

Beginning evidence-based scoring and annotation 
Error in object[object$cluster == clu.num[i], ] : 
  incorrect number of dimensions


Thank you

**Comment by ZJUFanLab** [comment]
You can try
`WT_baseline_clusters <- scCATCH(WT_baseline_all_markers$clu_markers, cancer = NULL, species = 'Mouse', tissue = 'Aorta')`

**Comment by rmondragon90** [comment]
The code is working now. Thank you so much!
