### ISSUE TITLE
cluster_data format

### ISSUE THREAD

**Issue by xiaoxiaofuyou** [ZJUFanLab/scCATCH#50]
Hello, It seems not mentioned the format of "cluster" in the tutorial. When I am trying to create a scCATCH object like this:
     **obj <- createscCATCH(data = BMcatch, cluster = BM@active.ident)**
I got this error:
   **Error in createscCATCH(data = BMcatch, cluster = BM@active.ident) : 
       cluster is not a character!**
So I want to know the specific cluster format, Thank you!

PS: BM is my Seurat object.

**Comment by xiaoxiaofuyou** [comment]
PS: BM is my Seurat object.

**Comment by multitalk** [comment]
Hello, you can try obj <- createscCATCH(data = BMcatch, cluster = as.character(BM@active.ident))

**Comment by xiaoxiaofuyou** [comment]
Oh, Thank you very much, it works!
