### ISSUE TITLE
更新版本后不能使用原来的Seurat格式的数据了吗

### ISSUE THREAD

**Issue by cherryamme** [ZJUFanLab/scCATCH#51]
这次更新取消了之前的Seurat格式直接使用。
建议tutorial 里加入从seurat开始的流程。
总觉得新建一个scCatch的格式，用泛函不是很必要，功能上比较单一。

**Comment by multitalk** [comment]
从seurat对象转过来也很简单，在readme里加了一行代码`obj <- createscCATCH(data = Seurat_obj[['RNA']]@data, cluster = as.character(Idents(Seurat_obj)))`
