### ISSUE TITLE
Can I work with seurat function FindAllMarkers

### ISSUE THREAD

**Issue by yugacandy** [ZJUFanLab/scCATCH#52]
Is it possible to replace findmarkergene() with FindAllMarkers() in Seurat library?
I think it is possible with lower vesions...(scCATCH function maybe) but I cannot find how to work with findcelltype()

**Comment by multitalk** [comment]
Hello, you can set the parameter `method` as `"2"` in the function of `findmarkergene`, which is to use `FindAllMarkers()` in `Seurat` to find marker genes.
```
findmarkergene(object = obj, method = "2")
```
