### ISSUE TITLE
No matched potential marker genes in the matrix!

### ISSUE THREAD

**Issue by Elena983** [ZJUFanLab/scCATCH#55]
```
Error in findmarkergene(object = obj, species = "Human", marker = cellmatch,  : 
  No matched potential marker genes in the matrix!
```

Hello

I received this error.
What can I do in this case?

**Comment by multitalk** [comment]
Do you define the parameter of `tissue` in `findmarkergene`. Generally, this function is used like the following：
```
obj <- findmarkergene(object = obj, species = "Human", marker = cellmatch, tissue = "Kidney")
```

**Comment by Elena983** [comment]
Yes
```
> obj <- findmarkergene(object = obj,
+                       species = "Human",
+                       marker = cellmatch,
+                       cancer = "Liver Cancer",
+                      tissue = "Liver")
Error in findmarkergene(object = obj, species = "Human", marker = cellmatch,  : 
  No matched potential marker genes in the matrix!
In addition: Warning message:
In .filter_marker(marker, species, cancer, tissue) :
  There are only 42 potential marker genes in CellMatch database for Human Liver Cancer on Liver!
```

**Comment by multitalk** [comment]
There are only 42 markers under this condtion. 
![image](https://user-images.githubusercontent.com/43984681/211196666-9960cc37-0a52-4f32-9104-ca4d70783f62.png)

Maybe you can try
```
obj <- findmarkergene(object = obj, species = "Human", marker = cellmatch, tissue = "Liver")
```

**Comment by Elena983** [comment]
![image](https://user-images.githubusercontent.com/68946912/211279725-fa9e8f43-76bd-4242-aea1-71bff4cb32c3.png)

**Comment by multitalk** [comment]
I doubt that the gene names in `obj` are not human's official symbols. Can you show me the `rownames(obj@data$ndata)[1:10]`?

**Comment by Elena983** [comment]
![image](https://user-images.githubusercontent.com/68946912/211802001-4c44eb87-7466-42d3-9ddc-50b6ee6f844c.png)

**Comment by multitalk** [comment]
The gene names are not human's official symbols! You should change them to human's or set a right `species`

**Comment by Elena983** [comment]
Give me example of these symbols please

**Comment by multitalk** [comment]
"BTG1", “C1QB”, "C1QC"
