### ISSUE TITLE
no method for coercing this S4 class to a vector

### ISSUE THREAD

**Issue by Elena983** [ZJUFanLab/scCATCH#57]
Hi

I tried to deal with the spatial data
<img width="545" alt="image" src="https://user-images.githubusercontent.com/68946912/215454957-8f198240-505b-4361-aebc-2a3d57c2c313.png">

Where can a mistake be?

**Comment by Elena983** [comment]
When I put my seurat object, I see this
<img width="621" alt="Screenshot 2023-01-30 at 14 44 09" src="https://user-images.githubusercontent.com/68946912/215494002-bc253569-721b-4eeb-8b95-063de09aa49c.png">

**Comment by ghost** [comment]
obj <- createscCATCH(data = vizgen.obj_RNA[['RNA']]@data, cluster = as.character(Idents(vizgen.obj_RNA[)))
obj <- findmarkergene(obj, species = "Human", marker = cellmatch, tissue = "Brain")

You did not use  the scCATCH obj you created in findmarkergene
