### ISSUE TITLE
scCATCH and Seurat

### ISSUE THREAD

**Issue by cathalgking** [ZJUFanLab/scCATCH#58]
How would I use scCATCH together with my data in a Seurat object for cell type annotation? I read the vignette but it does not seem to specify how to interact with a processed Seurat object. Is this possible? I am working with a Mouse colon dataset

**Comment by multitalk** [comment]
You can try
```
obj <- createscCATCH(data = Seurat_obj[['RNA']]@data, cluster = as.character(Idents(Seurat_obj)))
```

**Comment by cathalgking** [comment]
That seems to work, thanks. Is there a way that scCATCH can give a confidence score for each cell type call/annotation?
For example, for each cell, give a p-value or specificity score or something similar of how sure it is at each call.

**Comment by cathalgking** [comment]
After I create the scCATCH obj, I am having issues with the `findmarkergene()` function. I have not been able to found a solution online or elsewhere.
The code I am running is 
`A1_seu_sc <- findmarkergene(object = A1_seu_sc, species = "Mouse", marker = cellmatch, tissue = "Colorectum", use_method = 2)`

and

`A1_seu_sc <- findmarkergene(object = A1_seu_sc, species = "Mouse", marker = cellmatch, tissue = "Brain", use_method = 2)`
The error is shown in the below screenshot. I am working with data from a mouse colon (colonic cancer).

<img width="1016" alt="scCATCH" src="https://user-images.githubusercontent.com/32261323/220606393-eab47f45-0e4d-4a55-a6ca-2b837ecca1e4.png">

**Comment by multitalk** [comment]
You can try
```
A1_seu_sc <- findmarkergene(object = A1_seu_sc, species = "Mouse", marker = cellmatch, tissue = "Colon", use_method = 2)
```
https://github.com/ZJUFanLab/scCATCH/wiki/mouse_tissues

![image](https://user-images.githubusercontent.com/43984681/220867204-50751198-ce49-49eb-a1f3-596f21fe1071.png)

**Comment by cathalgking** [comment]
Ok, thanks @shaoxin0801.
When I run that, I get back a Warning message which says:

`Warning message:
In .filter_marker(marker, species, cancer, tissue) :
  There are only 8 potential marker genes in CellMatch database for Mouse on Colon!`
  
What exactly does this Warning mean? Does it mean that there is only 8 potential markers in **my** dataset that match with the list of markers in the CellMatch database? 
Is there a way to use all of the ''Intestine-related'' Mouse tissues for this? Assuming that will increase the number of markers found. 

When I do find an appropriate number of markers, how do I proceed to plot a UMAP plot with cell types labelled on the clusters? There does not seem to be an example of that in the Vignette. I presume it will be different to the standard Seurat `DimPlot()` function, as a new Formal class ''scCATCH'' object has been formed.

**Comment by multitalk** [comment]
You can try
```
tissuename <- c("Colon", "Colon epithelium", "Fetal intestine", "Gastrointestinal tract", "Ileum", "Intestinal crypt", "Intestine", "Mesenteric lymph node", "Small intestine")

A1_seu_sc <- findmarkergene(object = A1_seu_sc, 
                                                 species = "Mouse",
                                                 marker = cellmatch,
                                                 tissue = tissuename,
                                                 use_method = 2)
```

**Comment by cathalgking** [comment]
Ok that worked @shaoxin0801 

Now how can I plot or overlay the found cell types on the UMAP in my object? A seperate scCATCH object has been made so I presume it needs to interact with the original Seurat object in some way?

**Comment by multitalk** [comment]
Yes, you should use the label to plot with the original Seurat object
