### ISSUE TITLE
error from rev_gene function

### ISSUE THREAD

**Issue by februaryfang** [ZJUFanLab/scCATCH#59]
hello, 

I met an error from rev_gene function.
![image](https://user-images.githubusercontent.com/13863155/223049100-5d8f54f6-b5f4-4d86-9772-275646b2eb62.png)
![image](https://user-images.githubusercontent.com/13863155/223049398-f974da41-b412-44c2-b256-500d430d029c.png)

> rev_gene(data = demo_markers, data_type='marker', species = "Human", geneinfo = geneinfo)
Error in `$<-.data.frame`(`*tmp*`, "ligand", value = "KRT5") :
  replacement has 1 row, data has 0

![1678089100238](https://user-images.githubusercontent.com/13863155/223049822-c02bf75d-7287-4eb8-851b-c6ea0885a079.jpg)

Is it a bug?

Package: scCATCH
Version: 3.2.1
Repository: CRAN
Built: R 4.2.2;

**Comment by multitalk** [comment]
Thanks for your careful review. I have fixed the bug. :) @februaryfang
