### ISSUE TITLE
Error in genedata1$Var1 : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by rhart604** [ZJUFanLab/scCATCH#6]
I'm getting this error shortly after starting findmarkergenes().  I used a Seurat object with 2000 features (I subsetted for the VariableFeatures() of the object) and 277292 samples.  The object has been normalized and scaled.  

I'm using: Seurat_3.1.4 and scCATCH_2.0 in R 3.6.3 on a Windows 10 system.

**Comment by rhart604** [comment]
Resolved issue with appropriate capitalization of options. Species must be like "Mouse" but not "mouse".  Cluster must be "All" but not "ALL".  And so on.

**Comment by najeha13** [comment]
I keep getting the same error as well. I used a Seurat object of 593 cells and around 20k features. The object has been normalized and scaled. And also checked for appropriate capitalization.

**Comment by maryam1717** [comment]
@rhart604 
 Hello, I have the same problem but I wrote the names correctly. I have normalized and clustered Seurat object for human and tissue is a liver.
Error in genedata1$Var1 : $ operator is invalid for atomic vectors

**Comment by wolf5996** [comment]
@rhart604 
I am also having this issue even though I have written all the names correctly. Here is my code:

`clu_markers <- scCATCH::findmarkergenes(object = HCC1806I, 
                         species = "Human",
                         cluster = "All",
                         match_CellMatch = F, logfc = 0.25)
`

This throws at me the same error, and I am not sure why.
