### ISSUE TITLE
An error appeared when  running findmarkergene()

### ISSUE THREAD

**Issue by ZhengYingqi-doctor** [ZJUFanLab/scCATCH#60]
> test.catch <- findmarkergene(
+                     test.catch,
+                     species = 'Human',
+                     cluster = "All",
+                     if_use_custom_marker = FALSE,
+                     marker = cellmatch,
+                     cancer = "Hepatocellular Cancer",
+                     tissue = "Liver",
+                     use_method = "1",
+                     cell_min_pct = 0.25,
+                     logfc = 0.25,
+                     pvalue = 0.05,
+                     verbose = TRUE
+                   )
There are 797 potential marker genes in CellMatch database for Human Hepatocellular Cancer on Liver.
Error in apply(ndata2, 1, mean) : dim(X) must have a positive length
In addition: Warning message:
In asMethod(object) :
  sparse->dense coercion: allocating vector of size 3.1 GiB

**Comment by multitalk** [comment]
Hello, you can check the `table(test.catch@meta$cluster)` to see the number of each cluster first.
