### ISSUE TITLE
Inconsistent logFC calculation method

### ISSUE THREAD

**Issue by februaryfang** [ZJUFanLab/scCATCH#62]
In the paper :
![image](https://user-images.githubusercontent.com/13863155/234169315-726068c2-80e7-4203-a784-78ac09e73e5b.png)

In the script utils.R :
![image](https://user-images.githubusercontent.com/13863155/234169454-fb31829d-4c44-47f2-87d0-dd206242e57a.png)
![image](https://user-images.githubusercontent.com/13863155/234169560-084c8b7d-e79c-41a0-8663-6a5dd559fec4.png)

What is the reason for this?

**Comment by multitalk** [comment]
Sorry that this is a typo. We mean the log1p fold change.

**Comment by Leorio183** [comment]
I still can't understand, what is the real base in the R package? 10 or 2? I can't understand your answer "log1p fold change"
