### ISSUE TITLE
Issue with scCATCH  undefined columns selected

### ISSUE THREAD

**Issue by yaoxucpu** [ZJUFanLab/scCATCH#8]
Hello, I am having the following error when running scCATCH:

> all_markers <- findmarkergenes(data8,
+                                species = 'Mouse',
+                                cluster = '1',
+                                match_CellMatch = TRUE,
+                                cancer = 'Pancreatic Cancer',
+                                tissue = 'Blood',
+                                cell_min_pct = 0.25,
+                                logfc = 0.25,
+                                pvalue = 0.05)
Note: the raw data matrix includes 10533 cells and 19190 genes. 

---Revising gene symbols according to NCBI Gene symbols (updated in Jan. 10, 2020, https://www.ncbi.nlm.nih.gov/gene) and no matched genes and duplicated genes will be removed. 

Note: the new data matrix includes 10533 cells and 18357 genes. 

Warning: there are only 1 potential marker genes in CellMatch database for Mouse Pancreatic Cancer on Blood! 

Finding potential marker genes for cluster 1 
Error in `[.data.frame`(ndata, , clu_info[clu_info$cluster == clu_pair1$cluster1[j],  : 
  undefined columns selected

**Comment by ZJUFanLab** [comment]
Hello,  I want to know how many clusters does the data8 have? Besides, from the current results that there are only 1 potential marker genes in CellMatch database for Mouse Pancreatic Cancer on Blood, it may be not proper for your data to run scCACTH pipeline.

**Comment by yaoxucpu** [comment]
Thank you very much.
data8 has 17 clusters.  I use the raw data of mouse pancreatic tumor cells (GSE126539). There is only one marker genes in CellMatch database for Mouse Pancreatic Cancer on Blood. The results didn't make sense.

**Comment by ZJUFanLab** [comment]
As you know, CellMatch contains those literature-supported  marker genes. But we found that there are not sufficient marker genes for Mouse Pancreatic Cancer on Blood when we previously collected marker genes because there are limited research articles about Mouse Pancreatic Cancer resulting the limited reported marker genes for Mouse Pancreatic Cancer. You can try other annotating methods such as SingleR, scMap or CellAssign.

**Comment by yaoxucpu** [comment]
You are right, there are not sufficient marker genes published for my study, I will try other methods. Many thanks for your reply.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dr. FAN, Xiaohui <notifications@github.com>
发送时间: Thursday, April 30, 2020 10:39:08 PM
收件人: ZJUFanLab/scCATCH <scCATCH@noreply.github.com>
抄送: yaoxucpu <yaoxucpu@outlook.com>; Author <author@noreply.github.com>
主题: Re: [ZJUFanLab/scCATCH] Issue with scCATCH undefined columns selected (#8)


As you know, CellMatch contains those literature-supported marker genes. But we found that there are not sufficient marker genes for Mouse Pancreatic Cancer on Blood when we previously collected marker genes because there are limited research articles about Mouse Pancreatic Cancer resulting the limited reported marker genes for Mouse Pancreatic Cancer. You can try other annotating methods such as SingleR, scMap or CellAssign.

―

**Comment by ZJUFanLab** [comment]
You are welcome! We will expand our CellMatch database as we can in the future.
