### ISSUE TITLE
How to prepare a Seurat object containing log10 normalized single-cell transcriptomic data matrix

### ISSUE THREAD

**Issue by wolfQK** [ZJUFanLab/scCATCH#9]
I got a Seurat object containing log1p normalized single-cell transcriptomic data with Seurat default normalized method, how can I get a Seurat object containing log10 normalized ?  Can I use log1p normalized object in findmarkergenes by set  parameters in this function (You said object obtained from SCTransform can also be used by setting parameter logfc)?

**Comment by ZJUFanLab** [comment]
what is log1p?

**Comment by wolfQK** [comment]
Thank you for your prompt response !
      natural-log,  log or log1p in R.
      It is used in NormalizeData, the "LogNormalize"  method in Seurat.
      If I got the Seurat object with all default paramerents, how can I use your useful package ?
Thanks !

**Comment by ZJUFanLab** [comment]
Okay, I see. log1p is log(10)1p. If you got the Seurat object with all default paramerents, then you can usd scCATCH with default logfc cut off is the same with the `FindAllMarker` of Seurat, What I understand previously was that it was a log(2)Counts data matrix you were going to use.

**Comment by wolfQK** [comment]
It seems to be ln, not log10().  I tried the folowing in R,
> log1p(10)
[1] 2.397895
> log(10)
[1] 2.302585
> log10(10)
[1] 1

Seurat help document: "LogNormalize: Feature counts for each cell are divided by the total counts for that cell and multiplied by the scale.factor. This is then natural-log transformed using log1p."

I found this (Please ensure data is log10 normalized data) in the  user's guide part.

So, I wonder if I can use my object as the input object of scCATCH?
Thank you !

**Comment by ZJUFanLab** [comment]
Yes, you can use your object as the input object of scCATCH. Because the logfc cut off is the same with the FindAllMarker of Seurat. Acutally, what I meant is the log1p data matrix, and I wrote it wrong in the  user's guide part. Thanks for your careful review.

**Comment by wolfQK** [comment]
Thanks a lot !

**Comment by jgamache014** [comment]
@wolfQK mentioned in their initial question "You said object obtained from SCTransform can also be used by setting parameter logfc". 

What should the logfc parameter be set to if using an SCTransformed Seurat object?
